// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAQBmelWrIhx44kc83YVoario4Y36ehkY',
    appId: '1:1092819690261:web:8fd015946b0f08f490bf1c',
    messagingSenderId: '1092819690261',
    projectId: 'bookrental-665e5',
    authDomain: 'bookrental-665e5.firebaseapp.com',
    storageBucket: 'bookrental-665e5.appspot.com',
    measurementId: 'G-T0EQ61P27E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAR7UEUVksrGdLJyUm-srmLk9x6u2N7YQ',
    appId: '1:1092819690261:android:01b91758cb9185b590bf1c',
    messagingSenderId: '1092819690261',
    projectId: 'bookrental-665e5',
    storageBucket: 'bookrental-665e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGljMI1LNlBq35Z_9L9bBQ9dkcdDvuo14',
    appId: '1:1092819690261:ios:ed99fdf2d74ea39790bf1c',
    messagingSenderId: '1092819690261',
    projectId: 'bookrental-665e5',
    storageBucket: 'bookrental-665e5.appspot.com',
    iosBundleId: 'com.example.bookRental',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGljMI1LNlBq35Z_9L9bBQ9dkcdDvuo14',
    appId: '1:1092819690261:ios:44e3c9c23132562290bf1c',
    messagingSenderId: '1092819690261',
    projectId: 'bookrental-665e5',
    storageBucket: 'bookrental-665e5.appspot.com',
    iosBundleId: 'com.example.bookRental.RunnerTests',
  );
}
